export * from '@aurelia/kernel';
export * from '@aurelia/metadata';
export * from '@aurelia/platform';
export * from '@aurelia/platform-browser';
export * from '@aurelia/runtime-html';
export * from '@aurelia/expression-parser';
export * from '@aurelia/template-compiler';
export * from '@aurelia/runtime';
export { isObject } from '@aurelia/kernel';
export { BindingMode, BindingCommand } from '@aurelia/runtime-html';
export { IPlatform } from '@aurelia/kernel';
